Added .NET
boldare/boldare-radar pull request #59
Opened 2022-08-23 09:08 UTC by Velorien

2022-08-23 10:41 UTC, stpdeveloping requested changes

2022-08-23 10:41 UTC, stpdeveloping commented on docs/tech/mvp/frameworks/dotnet.md
> +[.NET](https://dot.net) is a framework for writing _any_ type of application, including, but not limited to, console apps, mobile apps (with MAUI) web APIs (with ASP.NET Core), games (with Unity3D) a
Zmienilbym Krzyśku `Unity3D` na `Unity`, jako ze taka jest nazwa silnika i mozna w nim tworzyc takze gry 2D. Dodalbym jeszcze `or MonoGame`. [MonoGame](https://www.monogame.net/) to aktywnie rozwijany projekt open-source'owy, w ktorym mozemy stworzyc wlasny silnik.

2022-08-23 10:50 UTC, stpdeveloping commented on docs/tech/mvp/frameworks/dotnet.md
> +[.NET](https://dot.net) is a framework for writing _any_ type of application, including, but not limited to, console apps, mobile apps (with MAUI) web APIs (with ASP.NET Core), games (with Unity3D) a
Zmienilbym jeszcze `mobile apps (with MAUI)` na `mobile and desktop apps (with MAUI), ` (poza trescia dodalem jeszcze na koncu brakujacy przecinek).

2022-10-17 08:02 UTC, michalczmiel approved these changes

2022-10-17 08:02 UTC, merged